test:
	${MAKE} -C git-clone-related-test test
	${MAKE} -C resolve-adjacent-conflicts-test
	${MAKE} -C resolve-import-conflicts-test

clean:
	${MAKE} -C git-clone-related-test clean
	${MAKE} -C resolve-adjacent-conflicts-test
	${MAKE} -C resolve-import-conflicts-test
